### ISSUE TITLE
Dropdown select overflowing bottom of the external screen

### ISSUE THREAD

**Issue by penspinner** [TypeDuck-HK/TypeDuck-Mac#2]
Hi! Thanks so much for the work on TypeDuck!

I have an external monitor for my MacBook. On my external monitor, when the input text box is at the bottom of the screen, the TypeDuck dropdown select overflows down beneath the monitor screen. I've attached a screenshot of me typing in Discord:

![image](https://github.com/TypeDuck-HK/TypeDuck-Mac/assets/6811492/82f450b1-011e-4bc0-af32-8e0ef48cb1b2)

However, on my MacBook screen, the dropdown is working as expected. It auto shifts to the top like this:

<img width="361" alt="image" src="https://github.com/TypeDuck-HK/TypeDuck-Mac/assets/6811492/aa00d71e-215f-4de8-9e4e-3405c258c3f1">

**Comment by bingzheung** [comment]
Hi @penspinner 

Thank you for your feedback, I will have a look into it.

Does this happen in other apps as well? Or is it only Discord?

**Comment by penspinner** [comment]
Hi. It happens in other apps as well. Here's a screenshot of TypeDuck on Slack macOS:

![image](https://github.com/TypeDuck-HK/TypeDuck-Mac/assets/6811492/3070eb69-26a8-4ec1-82d1-b628fdb3d6bc)

**Comment by bingzheung** [comment]
> Hi. It happens in other apps as well. Here's a screenshot of TypeDuck on Slack macOS:

Thank you! @penspinner 

Since Discord and Slack are both Electron-based apps, I wonder if it happens in non-Electron-based apps as well? Such as Apple Pages, Keynote, Safari, etc.

This bug-fix may take longer, as I don't have any external monitor available.

**Comment by penspinner** [comment]
![image](https://github.com/TypeDuck-HK/TypeDuck-Mac/assets/6811492/fc962f21-d22e-4369-a738-29e71dc01c66)

Yes, it happens on Safari.

---

![image](https://github.com/TypeDuck-HK/TypeDuck-Mac/assets/6811492/b693ead9-d00b-4875-897f-412017351014)

I noticed it works with RIME keyboard though:

**Comment by bingzheung** [comment]
Thank you for such detailed information!

**Comment by bingzheung** [comment]
Hi @penspinner 

I just released a new version. Hopefully this bug has been fixed. Please give it a try.

**Comment by penspinner** [comment]
![image](https://github.com/TypeDuck-HK/TypeDuck-Mac/assets/6811492/5dc230fa-dcfe-4eba-ad29-3353a2589e39)

It's fixed! Thanks for everything and TypeDuck.
