### ISSUE TITLE
頭字母輸入用唔到分詞號（'）

### ISSUE THREAD

**Issue by chaaklau** [TypeDuck-HK/TypeDuck-Mac#3]
**輸入** ： B'O
**預期結果**：顯示以 B O 開頭雙音節詞語
**實際結果**：無顯示候選詞

**Comment by bingzheung** [comment]
Hi @chaaklau 

唔該晒提醒，我會做下改進。

**Comment by bingzheung** [comment]
版本 v1.2.1 應該修正咗呢個問題嘞。
